# Match tensor
## NOTE: no where close to fully functional.

In [1]:
import json
import os
import sys
import numpy as np
from gensim.models import Word2Vec
from keras.preprocessing import sequence
from keras.layers import merge, Dense, Input,Dropout, Embedding, LSTM, Bidirectional, Activation
from keras.layers import Conv2D
from keras.layers.merge import dot, multiply, add, concatenate
from keras.layers import Merge
from keras.layers.core import Lambda,Reshape, Flatten
from keras.layers.pooling import GlobalMaxPooling2D
from keras.models import Model
from keras.backend import transpose,batch_dot,expand_dims
from keras import optimizers
from HomeDepotCSVReader import HomeDepotReader
import Utilities
from DataPreprocessing import DataPreprocessing
from Feature_Word2Vec import Feature_Word2Vec
from AutomaticQueryExpansion import Word2VecQueryExpansion

Using TensorFlow backend.


In [2]:
# train_filename = '../data/train_play.csv'
# test_filename = '../data/test_play.csv'
# attribute_filename = '../data/attributes_play.csv'
# description_filename = '../data/product_descriptions_play.csv'
# word2vec_model_path='model/word2vec_play.model'
# vocab_path='model/word2vec_play_vocab.json'
# embeddings_path='model/embeddings_play.npz'

train_filename = '../data/train.csv'
test_filename = '../data/test.csv'
attribute_filename = '../data/attributes.csv'
description_filename = '../data/product_descriptions.csv'
word2vec_model_path='model/word2vec.model'
vocab_path='model/word2vec_vocab.json'
embeddings_path='model/embeddings.npz'

In [3]:
reader = HomeDepotReader()

train_query_df, product_df, attribute_df, test_query_df = reader.getQueryProductAttributeDataFrame(train_filename,
                                              test_filename,
                                              attribute_filename,
                                              description_filename)
print("train_query_df:",list(train_query_df))
print("product_df:", list(product_df))
print("attribute_df:", list(attribute_df))
print("test_query_df:", list(test_query_df))

===========Tranforming labels...
showing current values
trainDF: ['id', 'product_uid', 'search_term', 'relevance']
trainDF:    id  product_uid    search_term  relevance
0   2       100001  angle bracket        3.0
self.mergedLabelDF: ['relevance'] 
 <class 'pandas.core.frame.DataFrame'> (74067, 1)    relevance
0        3.0
Old unique Labels: [ 1.    1.25  1.33  1.5   1.67  1.75  2.    2.25  2.33  2.5   2.67  2.75
  3.  ]
newLabels: [ 0  1  2  3  4  5  6  7  8  9 10 11 12]
Creating new column for training:  relevance_int
===========Transform labels completed
train_query_df: ['id', 'product_uid', 'search_term', 'relevance', 'relevance_int', 'product_idx']
product_df: ['product_title', 'product_uid', 'product_description']
attribute_df: ['product_uid', 'name', 'value']
test_query_df: ['id', 'product_uid', 'search_term']


In [4]:
#transform attribute into doc
dp = DataPreprocessing()
attribute_doc_df = dp.getAttributeDoc(attribute_df)
#attribute_doc_df
product_df=product_df.join(attribute_doc_df.set_index('product_uid'), on = 'product_uid')

In [5]:
# product_df['content'] = train_query_df['search_term'].map(str) + " " + \
#                         product_df['product_title'].map(str) + " " + \
#                         product_df['product_description'].map(str) + " " + \
#                         product_df['attr_json'].map(str)

product_df['content'] = product_df['product_title'].map(str) + " " + \
                        product_df['product_description'].map(str) 

# ## no attribute
# product_df['content'] = product_df['product_title'].map(str) + " " + \
#                         product_df['product_description'].map(str) 
        
#product_df['content']

In [6]:
#w2v=Feature_Word2Vec(modelFilename=word2vec_model_path)#modelFilename=word2vec_model_path
w2v=Feature_Word2Vec()
sentences=w2v.convertDFIntoSentences(product_df,'content')
#print(sentences)
w2v.trainModel(sentences)

Loading Word2Vec model
Initialise/Train Word2Vec model
('Time taken: ', 1.5333333333333334, ' mins')
Saving vectors to disk
('Time taken: ', 0, ' secs')


In [7]:
len(w2v.model.wv.vocab)

72827

In [8]:
# w2vExpand=Word2VecQueryExpansion(modelFilename=word2vec_model_path)
# query="cooking"
# print("Expanding query: ")
# print(w2vExpand.getExpandedQuery(query,maxNoOfAdditionalWords=2,minSimilarityLevel=0.65,))

In [9]:
print(w2v.getVectorFromWord('wood'))
print(w2v.getSimilarWordVectors('wood',5))
print(len(w2v.getVectorFromWord('wood')))

[ 4.05043507  3.49019146 -0.06090352  1.71556103  2.35107517  2.13475037
 -1.92377174 -3.25637412  0.56044257 -0.40419373  1.90303624 -0.17706122
  2.54476619 -1.1679852  -1.04832709  0.46012864  1.18832374  1.28595293
  6.29103231  0.77106035 -4.03227377  1.97043014 -0.59022874 -3.17424178
 -0.36804637 -0.61262178 -0.75078177 -0.42666331  2.30822086 -4.05024481
  0.72244686  1.72640133 -1.25437295 -1.05009019 -2.08370948 -0.85143971
 -0.56405699  4.1177001   2.61707401  1.55357254 -2.06696749 -2.00102615
  0.48281354 -1.68158555  2.12631869  3.89384604 -0.43447676  0.97610545
 -2.19433045 -1.21479046 -4.6699028  -2.06615448  4.94874239 -0.38742435
 -2.90473318  2.34807134  2.0020256  -0.78927368 -0.1993627   2.29082036
  3.06380582  1.93890679  1.09457994  0.46953908  2.76734853  2.98501611
 -2.73549151 -1.32382369 -2.61912513 -0.74327958 -2.24027848  1.3900671
 -1.26408017  0.72640014  0.88561004  2.5344274  -3.36937737  2.88120604
 -1.90230823  3.23573303 -3.50353646 -0.34555268 -0.

# embeddings to keras
http://ben.bolte.cc/resources/embeddings/embeddings.html

In [10]:
vocab = dict([(k, v.index) for k, v in w2v.model.wv.vocab.items()])
with open(vocab_path, 'w') as f:
    f.write(json.dumps(vocab))

In [11]:
weights = w2v.model.wv.syn0
np.save(open(embeddings_path, 'wb'), weights)

In [12]:
def load_vocab(vocab_path):
    """
    Load word -> index and index -> word mappings
    :param vocab_path: where the word-index map is saved
    :return: word2idx, idx2word
    """

    with open(vocab_path, 'r') as f:
        data = json.loads(f.read())
    word2idx = data
    idx2word = dict([(v, k) for k, v in data.items()])
    return word2idx, idx2word

In [13]:
word2idx, idx2word = load_vocab(vocab_path)

In [14]:
def word2vec_embedding_layer(embeddings_path):
    """
    Generate an embedding layer word2vec embeddings
    :param embeddings_path: where the embeddings are saved (as a numpy file)
    :return: the generated embedding layer
    """

    weights = np.load(open(embeddings_path, 'rb'))
    layer = Embedding(input_dim=weights.shape[0], output_dim=weights.shape[1], weights=[weights])
    return layer

In [15]:
print_tokens=False

In [16]:
# variable arguments are passed to gensim's word2vec model
# if options.train:
#     print('Training Word2Vec...')
#     create_embeddings(options.data, options.embeddings, options.vocab, size=100, min_count=5, window=5, sg=1, iter=25)

word2idx, idx2word = load_vocab(vocab_path)

if print_tokens:
    print('Tokens:', ', '.join(word2idx.keys()))



# convert to idx

In [17]:
def query_sent2idx(df,col):
    query_word2vec_idx_list=[]
    queries=w2v.convertDFIntoSentences(df,col)
    print(len(queries))
    for query in queries:
        idx_list = []
        for word in query:
            if word not in word2idx.keys():
                idx_list+=[0]#[len(word2idx.keys())] # use last as special key #TODO: well we need to fix this. Using 0 for now so it's in range To OOV or something random
            else:
                idx_list+=[word2idx[word]]
        query_word2vec_idx_list+=[idx_list]
        #print("=====")
        #print(idx_list)
        #print("=====")
    return query_word2vec_idx_list


In [18]:
query_word2vec_idx_list = query_sent2idx(train_query_df,'search_term')
#print(query_word2vec_idx_list)

75575


In [19]:
# def doc_sent2idx(df,col):
#     doc_word2vec_idx_list=[]
#     for row in df.iteritems():
#         a=w2v.convertDFIntoSentences(row,col)
#         print(a)
# #    print(len(queries))
# #     for query in queries:
# #         idx_list = []
# #         for word in query:
# #             if word not in word2idx.keys():
# #                 idx_list+=[len(word2idx.keys())] # use last as special key
# #             else:
# #                 idx_list+=[word2idx[word]]
# #         query_word2vec_idx_list+=[idx_list]
# #         print("=====")
# #         print(idx_list)
# #         print("=====")
#     return doc_word2vec_idx_list

In [20]:
#TODO: this is fucked. just bodge for testing nn
doc_word2vec_idx_list = query_sent2idx(product_df,'product_title')
#print(doc_word2vec_idx_list)

277395


In [21]:
# # cosine similarity model
# print('Building model...')
# input_a = Input(shape=(1,), dtype='int32', name='input_a')
# input_b = Input(shape=(1,), dtype='int32', name='input_b')
# embeddings = word2vec_embedding_layer(embeddings_path)
# embedding_a = embeddings(input_a)
# embedding_b = embeddings(input_b)
# similarity = merge([embedding_a, embedding_b], mode='cos', dot_axes=2)
# model = Model(input=[input_a, input_b], output=similarity)
# model.compile(optimizer='sgd', loss='mse') # optimizer and loss don't matter


# word_a = 'wood'#raw_input('First word: ')
# if word_a not in word2idx:
#     print('"%s" is not in the index' % word_a)
# word_b = 'fan'#raw_input('Second word: ')
# if word_b not in word2idx:
#     print('"%s" is not in the index' % word_b)
# output = model.predict([np.asarray([word2idx[word_a]]), np.asarray([word2idx[word_b]])])
# print('%f' % output)

# Define model

In [22]:
query_max_len = 6 #covers 95.74% of the search lengths (see data exploration)
# find longest sub list
doc_max_len = len(max(doc_word2vec_idx_list,key=len)) #400 # todo: confirm this is sensible
print(doc_max_len)
print(query_max_len)

27
6


In [23]:
print('Building model...')

def get_R(x):
    a, b = x.values()
    return K.dot(a, b)


embeddings = word2vec_embedding_layer(embeddings_path)

#embedding lookup
# TODO: replace this with embedding with mask zero rather than padding, need to change index for encoding too, imput dim too.
# TODO: OOV embedding
input_query = Input(shape=(query_max_len,), dtype='int32', name='input_query')
input_doc = Input(shape=(doc_max_len,), dtype='int32', name='input_doc')
input_exact_match = Input(shape=(query_max_len,doc_max_len), dtype='float32', name='input_exact_match')
embedding_query = embeddings(input_query)  # (None, 6, 100)
embedding_doc = embeddings(input_doc)      # (None, 400, 100)

#shared linear projection
shared_lp = Dense(40,activation='linear')
query_output = shared_lp(embedding_query) # (None, 6, 40) 
doc_output = shared_lp(embedding_doc) #(None, 400, 40) 

#query: bi LSTM, lp -- implementation = 0 for CPU option, 1 or 2 for GPU
query_output = Bidirectional(LSTM(30, dropout=0.5, implementation=0, return_sequences=True, go_backwards=True)\
                             ,merge_mode='mul'#TODO: alts are 'sum','mul','ave','concat'<--default, None
                            )(query_output) #(None, 6, 30) unless concat (None, 6, 60)  
query_output = Dense(50,activation='linear')(query_output) #(None, 50)

#doc: bi LSTM, lp
doc_output = Bidirectional(LSTM(30, dropout=0.5, implementation=0, return_sequences=True, go_backwards=True)\
                             ,merge_mode='mul'#TODO: alts are 'sum','mul','ave','concat'<--default, None
                            )(doc_output) #(None, 6, 400) unless concat (None, 6, 800)  
doc_output = Dense(50,activation='linear')(doc_output) #(None, 50)

#2d product
#mt_input = batch_dot(query_output,doc_output,axes=None) #axes=[2,2])
#query_output = Flatten()(query_output)
#doc_output = Flatten()(doc_output)
#mt_input = multiply([query_output, doc_output])
#mt_input = dot([query_output, doc_output], axes=(0), normalize=False)  
dot_product_output = dot([query_output, doc_output], axes=(2), normalize=True)  
#output is (11, 6, 400), where did 50 go?
def func_expand_dims(x):
    return expand_dims(x, axis=-1)

def expand_dims_output_shape(input_shape):
    return (input_shape[0], input_shape[1],input_shape[2],1)

mt_input_1 = Lambda(func_expand_dims, expand_dims_output_shape)(dot_product_output)

#mt_input = dot([transpose(query_output), transpose(doc_output)], axes=(0), normalize=False)  
######################################

def state_layer_dot_prod(x):
    output_list=[]
#    output = dot([x[0], x[1]], axes=(2), normalize=False)  
    for i in range(50):
        print(i)
        print(x[0][i])
        print(x[1][i])
        #output = multiply([transpose(x[0][i]), x[1][i]])
        #output_list += output
        #output = dot([x[0][i], transpose(x[1][i])])
        #transpose(x[1][i])
    print(output_list)
    return output_list

def state_layer_dot_prod_shape(input_shape):
    'Merge output shape'
    shape = list(input_shape)
    #print(input_shape)
    #print(shape)
    outshape = (shape[0][0],shape[1][1],shape[0][1],shape[0][2])
    #print(outshape)
    return tuple(outshape)

######################################
#mt_input = Lambda(state_layer_dot_prod,output_shape=state_layer_dot_prod_shape)([transpose(query_output), transpose(doc_output)])
#mt_input = Lambda(state_layer_dot_prod,output_shape=state_layer_dot_prod_shape)([query_output, doc_output])

##TODO fix error:
#InvalidArgumentError: Input to reshape is a tensor with 4800 values, but the requested shape requires a multiple of 120000
#[[Node: reshape_23/Reshape = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/cpu:0"](lambda_40/dot_42/MatMul, reshape_23/Reshape/shape)]]
#mt_input = Reshape((doc_max_len, query_max_len,50))(mt_input)

#Append exact match channel
output_exact_match = Dense(doc_max_len,activation='linear')(input_exact_match)
mt_input_2 = Lambda(func_expand_dims, expand_dims_output_shape)(output_exact_match)
# mt_input = concatenate([mt_input_1,mt_input_2],axis=0)
mt_input = concatenate([mt_input_1,mt_input_2],axis=3)

# Conv layers 1
output1 = Conv2D(filters=18, kernel_size=(3, 3), strides=(1,1), padding='valid', data_format='channels_last', \
                dilation_rate=(1, 1), activation='relu', use_bias=True, kernel_initializer='glorot_uniform', \
                bias_initializer='zeros', kernel_regularizer=None, bias_regularizer=None, \
                activity_regularizer=None, kernel_constraint=None, bias_constraint=None)(mt_input)

output2 = Conv2D(filters=18, kernel_size=(3, 4), strides=(1,1), padding='valid', data_format='channels_last', \
                dilation_rate=(1, 1), activation='relu', use_bias=True, kernel_initializer='glorot_uniform', \
                bias_initializer='zeros', kernel_regularizer=None, bias_regularizer=None, \
                activity_regularizer=None, kernel_constraint=None, bias_constraint=None)(mt_input)

output3 = Conv2D(filters=18, kernel_size=(3, 5), strides=(1,1), padding='valid', data_format='channels_last', \
                dilation_rate=(1, 1), activation='relu', use_bias=True, kernel_initializer='glorot_uniform', \
                bias_initializer='zeros', kernel_regularizer=None, bias_regularizer=None, \
                activity_regularizer=None, kernel_constraint=None, bias_constraint=None)(mt_input)

# Conv layers 2
output1 = Conv2D(filters=20, kernel_size=(1, 1), strides=(1,1), padding='valid', data_format='channels_last', \
                dilation_rate=(1, 1), activation='relu', use_bias=True, kernel_initializer='glorot_uniform', \
                bias_initializer='zeros', kernel_regularizer=None, bias_regularizer=None, \
                activity_regularizer=None, kernel_constraint=None, bias_constraint=None)(output1)

output2 = Conv2D(filters=20, kernel_size=(1, 1), strides=(1,1), padding='valid', data_format='channels_last', \
                dilation_rate=(1, 1), activation='relu', use_bias=True, kernel_initializer='glorot_uniform', \
                bias_initializer='zeros', kernel_regularizer=None, bias_regularizer=None, \
                activity_regularizer=None, kernel_constraint=None, bias_constraint=None)(output2)

output3 = Conv2D(filters=20, kernel_size=(1, 1), strides=(1,1), padding='valid', data_format='channels_last', \
                dilation_rate=(1, 1), activation='relu', use_bias=True, kernel_initializer='glorot_uniform', \
                bias_initializer='zeros', kernel_regularizer=None, bias_regularizer=None, \
                activity_regularizer=None, kernel_constraint=None, bias_constraint=None)(output3)

# Max pool layer
output1 = GlobalMaxPooling2D(data_format='channels_last')(output1)
output2 = GlobalMaxPooling2D(data_format='channels_last')(output2)
output3 = GlobalMaxPooling2D(data_format='channels_last')(output3)

# Merge
output_combined = add([output1,output2,output3])

# Final layer
output = Dense(1,activation='sigmoid')(output_combined)


# build model
#model = Model([input_query], [query_output])
#model = Model([input_doc], [encoded_doc])
#model = Model([input_query,input_doc], [output1,output2,output3])
#model = Model([input_query,input_doc], [output_combined])
#model = Model([input_query,input_doc], [query_output])
#model = Model([input_query,input_doc], [query_output,doc_output])
#model = Model([input_query,input_doc], [output])
#model = Model([input_query,input_doc,input_exact_match], [mt_input])
#model = Model([input_query,input_doc,input_exact_match], [mt_input_1,mt_input_2])
model = Model([input_query,input_doc,input_exact_match], [output])


model.summary()

Building model...
____________________________________________________________________________________________________
Layer (type)                     Output Shape          Param #     Connected to                     
input_query (InputLayer)         (None, 6)             0                                            
____________________________________________________________________________________________________
input_doc (InputLayer)           (None, 27)            0                                            
____________________________________________________________________________________________________
embedding_1 (Embedding)          multiple              7282700                                      
____________________________________________________________________________________________________
dense_1 (Dense)                  multiple              4040                                         
_________________________________________________________________________

In [24]:
# # from keras.layers import Input, merge
# # from keras.models import Model
# # import numpy as np

# # input_a = np.reshape([[1, 2, 3],[1, 2, 3],],[[1, 2, 3],[1, 2, 3]])
# # input_b = np.reshape([4, 5, 6], (1, 1, 3))

# # print(input_a)
# # print(input_b)
# # a = Input(shape=(1, 3))
# # b = Input(shape=(1, 3))

# # concat = merge([a, b], mode='concat', concat_axis=-1)
# # dot = merge([a, b], mode='dot', dot_axes=2)
# # cos = merge([a, b], mode='cos', dot_axes=2)

# # model_concat = Model(input=[a, b], output=concat)
# # model_dot = Model(input=[a, b], output=dot)
# # model_cos = Model(input=[a, b], output=cos)

# # print(model_concat.predict([input_a, input_b]))
# # print(model_dot.predict([input_a, input_b]))
# # print(model_cos.predict([input_a, input_b]))

# from keras import backend as K
# x_batch = K.ones(shape=(11, 6,50 ))
# y_batch = K.ones(shape=(11, 400,50))
# x_batch=K.batch_flatten(x_batch)
# y_batch=K.batch_flatten(y_batch)
# #xy_batch_dot = K.dot(transpose(y_batch),x_batch )#, axes=[0,0])
# xy_batch_dot = K.batch_dot(x_batch,y_batch, axes=[0,0])
# K.int_shape(xy_batch_dot)
# # K.int_shape(x_batch)
# # K.int_shape(y_batch)



In [25]:
optimizer = optimizers.Adam(lr=0.001)
model.compile(optimizer=optimizer, loss='mse', metrics=['accuracy'])

In [26]:
x_query_train=np.array(query_word2vec_idx_list)[0:74067]
x_doc_train=np.array(doc_word2vec_idx_list)[0:74067]#[0:len(x_query_train)]

# TODO: replace this with embedding with mask zero rather than padding, need to change index for encoding too, imput dim too.
print("Pad sequences (samples x time)")
x_query_train = sequence.pad_sequences(x_query_train, maxlen=query_max_len)
x_doc_train = sequence.pad_sequences(x_doc_train, maxlen=doc_max_len)
# x_query_test = sequence.pad_sequences(x_query_test, maxlen=query_max_len)
# x_doc_test = sequence.pad_sequences(x_doc_test, maxlen=doc_max_len)

print('x_query_train shape:', x_query_train.shape)
print('x_doc_train shape:', x_doc_train.shape)
# print('x_query_test shape:', x_query_test.shape)
# print('x_doc_test shape:', x_doc_test.shape)

#TODO: y label on 0-1 scale
y_train=train_query_df['relevance'].as_matrix()/3
#y_train=train_query_df['relevance_int'].as_matrix()
# y_test=test_query_df['relevance_int'].as_matrix()
print('y_train shape:', y_train.shape)

Pad sequences (samples x time)
x_query_train shape: (74067, 6)
x_doc_train shape: (74067, 27)
y_train shape: (74067,)


In [27]:
len(max(query_word2vec_idx_list,key=len)) 

11

In [28]:
exact_match_list=[]
for i in range(x_query_train.shape[0]):
    #print(i)
    c1=x_query_train[i]
    c2=x_doc_train[i]
    #print(c1.shape[0])
    #print(c2.shape[0])

    c1_inp=np.repeat(c1,c2.shape[0],axis=0)
    c1_inp=c1_inp.reshape((c1.shape[0],c2.shape[0]))
    #print(c1_inp.shape)
    #print(c1_inp)

    #print(c2)
    c2_inp=np.tile(c2,(c1.shape[0],1))
    #print(c2_inp.shape)
    #print(c2_inp)    
    #print(c1_inp == c2_inp)
    exact_match_list+=[(c1_inp == c2_inp).astype(int)]

In [29]:
exact_match_inp_train=np.array(exact_match_list)

In [30]:
exact_match_inp_train.shape

(74067, 6, 27)

In [31]:
print(train_query_df['search_term'][0])
print(product_df['product_title'][0])
print(x_query_train[i])
print(x_doc_train[i])
print(exact_match_inp_train[0])


angle bracket
Simpson Strong-Tie 12-Gauge Angle
[   0    0    0 1248  416    0]
[   0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0 2378  443  179 9680  978   28  315   33  356   77]
[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [33]:
batch_size=100#2
print('Train...')
hist=model.fit([x_query_train,x_doc_train,exact_match_inp_train], [y_train],
          batch_size=batch_size,
          epochs=3,
          validation_split=0.2,
          shuffle=True,
          verbose=2,
          #validation_data=[x_test, y_test])
         )


Train...
Train on 59253 samples, validate on 14814 samples
Epoch 1/3
72s - loss: 0.0319 - acc: 0.2899 - val_loss: 0.0345 - val_acc: 0.1316
Epoch 2/3
70s - loss: 0.0315 - acc: 0.2899 - val_loss: 0.0346 - val_acc: 0.1316
Epoch 3/3
70s - loss: 0.0314 - acc: 0.2899 - val_loss: 0.0326 - val_acc: 0.1316


In [35]:
batch_size=100
prediction=model.predict([x_query_train,x_doc_train,exact_match_inp_train],
          batch_size=batch_size,
         )

In [36]:
prediction.shape

(74067, 1)

In [37]:
prediction

array([[ 0.79610896],
       [ 0.79341847],
       [ 0.79600668],
       ..., 
       [ 0.80529708],
       [ 0.77157462],
       [ 0.79347754]], dtype=float32)

In [ ]:
print("Predict")
word_a = 'wood'#raw_input('First word: ')
if word_a not in word2idx:
    print('"%s" is not in the index' % word_a)
word_b = 'fan'#raw_input('Second word: ')
if word_b not in word2idx:
    print('"%s" is not in the index' % word_b)
output = model.predict([np.asarray([word2idx[word_a]]), np.asarray([word2idx[word_b]])])
print('%f' % output)